# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export HOSTNAME="$HOST"
export HISTFILE="${ZDATADIR}/zsh_history"
export HISTSIZE=10000
export SAVEHIST=100000
export HISTORY_IGNORE="(ls|ls -al|cd|pwd|zsh|exit|cd ..|gsb|gaa)"
export LISTMAX=1000

autoload -Uz compinit && compinit -u

# Powerlevel10k
source ~/ghq/github.com/marcoluzi/macos-dotfiles/powerlevel10k/powerlevel10k.zsh-theme

# zsh-syntax-highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# zsh-autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# omz git plugin
source $HOME/.dotfiles/ohmyzsh/lib/git.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/git/git.plugin.zsh

# omz plugin
source $HOME/.dotfiles/ohmyzsh/plugins/brew/brew.plugin.zsh

# omz common aliases plugin
source $HOME/.dotfiles/ohmyzsh/plugins/common-aliases/common-aliases.plugin.zsh

# omz aliases plugin
source $HOME/.dotfiles/ohmyzsh/plugins/aliases/aliases.plugin.zsh

# omz alias-finder plugin
source $HOME/.dotfiles/ohmyzsh/plugins/alias-finder/alias-finder.plugin.zsh
zstyle ':omz:plugins:alias-finder' autoload yes
zstyle ':omz:plugins:alias-finder' longer yes
zstyle ':omz:plugins:alias-finder' exact yes
zstyle ':omz:plugins:alias-finder' cheaper yes

# omz rsync plugin
source $HOME/.dotfiles/ohmyzsh/plugins/rsync/rsync.plugin.zsh

# omz thefuck plugin
source $HOME/.dotfiles/ohmyzsh/plugins/thefuck/thefuck.plugin.zsh

# fnm setup
eval "$(fnm env --use-on-cd)"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
